# pyrefly: ignore [missing-import]
from sqlalchemy import Column, Integer, String, Text, DateTime
# pyrefly: ignore [missing-import]
from sqlalchemy.orm import declarative_base
import datetime

Base = declarative_base()

class Conversation(Base):
    """
    Unified schema representing a user conversation/review scraped from any source.
    """
    __tablename__ = 'conversations'

    id = Column(Integer, primary_key=True, autoincrement=True)
    source = Column(String(100), nullable=False)  # e.g., "Google Play", "App Store", "Reddit"
    source_type = Column(String(50), nullable=False)  # e.g., "Review", "Post", "Comment"
    url = Column(String(500), nullable=True)  # URL to the specific post/review, if applicable
    timestamp = Column(DateTime, nullable=False)  # When the post/review was created
    raw_text = Column(Text, nullable=False)  # The actual user complaint or text
    ingested_at = Column(DateTime, default=datetime.datetime.utcnow)  # Timestamp of ingestion
    is_processed = Column(Integer, default=0) # 0 for False, 1 for True

    def __repr__(self):
        return f"<Conversation(source='{self.source}', source_type='{self.source_type}', timestamp='{self.timestamp}')>"

class Insight(Base):
    """
    Schema for storing the structured deep retrieval analytics generated by Groq.
    """
    __tablename__ = 'insights'

    id = Column(Integer, primary_key=True, autoincrement=True)
    conversation_id = Column(Integer, nullable=False) # Foreign key equivalent to Conversation.id
    
    retrieval_struggle = Column(String(200), nullable=True)
    remembered_info = Column(Text, nullable=True)
    forgotten_info = Column(Text, nullable=True)
    search_formulation = Column(Text, nullable=True)
    opportunity_area = Column(String(200), nullable=True)
    exact_quote = Column(Text, nullable=False) # Kept for zero-hallucination verification
    
    created_at = Column(DateTime, default=datetime.datetime.utcnow)
    pm_status = Column(String(50), default="Needs Review") # "Needs Review", "Accepted", "Rejected", "Needs Research"
    pm_feedback = Column(Text, nullable=True)

    def __repr__(self):
        return f"<Insight(opportunity='{self.opportunity_area}')>"

class ProblemCluster(Base):
    """
    Schema for discovered problem clusters formed from grouped Insights.
    """
    __tablename__ = 'problem_clusters'

    id = Column(Integer, primary_key=True, autoincrement=True)
    title = Column(String(200), nullable=False)
    statement = Column(Text, nullable=False)
    situation = Column(Text, nullable=True)
    remembered_info = Column(Text, nullable=True)
    missing_info = Column(Text, nullable=True)
    typical_attempt = Column(Text, nullable=True)
    typical_failure = Column(Text, nullable=True)
    affected_content = Column(Text, nullable=True)
    
    evidence_count = Column(Integer, default=0)
    independent_source_count = Column(Integer, default=0)
    confidence_score = Column(String(50), default="MEDIUM") # "HIGH", "MEDIUM", "LOW"

    def __repr__(self):
        return f"<ProblemCluster(title='{self.title}')>"

class Opportunity(Base):
    """
    Schema for opportunities identified from problem clusters.
    """
    __tablename__ = 'opportunities'

    id = Column(Integer, primary_key=True, autoincrement=True)
    cluster_id = Column(Integer, nullable=False)
    opportunity_area = Column(String(200), nullable=False)
    affected_users = Column(Text, nullable=True)
    evidence_strength = Column(String(50), default="MEDIUM")
    prevalence = Column(String(100), nullable=True)
    retrieval_relevance = Column(String(50), default="HIGH")

    def __repr__(self):
        return f"<Opportunity(area='{self.opportunity_area}')>"
